server:
  port: 4004 # Gateway listens on port 4004

spring:
  cloud:
    gateway:
      routes:

        - id: auth-service-route
          uri: http://host-docker.internal:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # Route for /api/user/** to user-service
        - id: user-service-route
          uri: http://host-docker.internal:4000
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Route for /api/docs/users to user-service /v3/api-docs
        - id: api-docs-user-route
          uri: http://host-docker.internal:4000
          predicates:
            - Path=/api-docs/users
          filters:
            - RewritePath=/api-docs/users,/v3/api-docs


        - id: api-docs-auth-route
          uri: http://host-docker.internal:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs